name: sa_battery_plus_listener_lego
description: "battery listener lego under simple architecture framework"
#publish_to: 'none'
repository: https://github.com/flutter-lego/sa_battery_plus_listener_lego

version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: #@add
  gap: #@add
  june_flow_util:
  styled_widget: #@add
  modal_bottom_sheet: #@add
  keyboard_attachable: #@add
  flutter_zoom_drawer: #@add
  flutter_screenutil:
  bot_toast:
  battery_plus: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  screenutil_lego: #@add
  bot_toast_lego: #@add
  listener_lego: #@add

flutter:
  assets:
    - assets/lego/sa_battery_plus_listener_lego/
  uses-material-design: true

topics:
  - lego